version: '3'
services:
  postgres:
    image: "postgres:latest"
    volumes:
      - ./postgres-schema/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
  mastercard-service:
    build: ./mastercard-service/
    ports:
    - "8081:8080"
  client-account-service:
    build: ./client-account-service/
    ports:
    - "8082:8080"

volumes:
  postgres-schema:

