version: '3'
services:
  postgres:
    image: "postgres:latest"
    volumes:
      - ./schema/:/docker-entrypoint-initdb.d/
    ports:
    - "5431:5432"
  mastercard-service:
    build: .
    depends_on:
    - postgres
    ports:
    - "8081:8080"

volumes:
  schema:
